package cn.edu.bupt;

/**
 * Created by FirenzesEagle on 2016/11/29.
 * Email:liumingbo2008@gmail.com
 */

/*389. Find the Difference
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class Find_the_Difference {
    public char findTheDifference(String s, String t) {
        int[] hash = new int[26];
        char[] sArray = s.toCharArray();
        char[] tArray = t.toCharArray();
        for (int i = 0; i < sArray.length; i++) {
            int num = sArray[i] - 'a';
            hash[num]++;
        }
        for (int i = 0; i < tArray.length; i++) {
            int num = tArray[i] - 'a';
            hash[num]--;
            if (hash[num] < 0) {
                return (char) (num+'a');
            }
        }
        return ' ';
    }
}
